version: '3.7'

services:
  app_mysql:
    image: mysql:latest
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "11001:3306"

  rabbitmq:
    image: rabbitmq:latest
    container_name: 'rabbitmq'
    ports:
      - "11002:5672"
      - "11003:15672"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "11004:1025"
      - "11005:8025"